version: '3.1'

services:

  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    expose:
      - "5432"
    ports:
      - "5432:5432"